USE AdventureWorks2017;
IF OBJECT_ID('CLAIMTRACKER.Comments','U') 
	IS NOT NULL DROP TABLE ClaimTracker.Comments;
IF OBJECT_ID('CLAIMTRACKER.Claim_Tracker','U') 
	IS NOT NULL DROP TABLE ClaimTracker.Claim_Tracker;
IF OBJECT_ID('CLAIMTRACKER.ANALYTICS','U') 
	IS NOT NULL DROP TABLE ClaimTracker.Analytics;
IF OBJECT_ID('CLAIMTRACKER.Id_Systems','U') 
	IS NOT NULL DROP TABLE ClaimTracker.Id_Systems;
IF OBJECT_ID('CLAIMTRACKER.Claim_Processing_Systems','U') 
	IS NOT NULL DROP TABLE ClaimTracker.Claim_Processing_Systems;
	GO
CREATE TABLE ClaimTracker.Id_Systems (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
,ID_SYSTEM VARCHAR(15)
);

INSERT INTO ClaimTracker.Id_Systems (ID_SYSTEM) 
	VALUES('Claim Miner'),('IDWS'),('CCAT'),('Devlin'),('ODAR')

CREATE TABLE ClaimTracker.Analytics(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
,ID_SYSTEM_ID INT NOT NULL FOREIGN KEY REFERENCES ClaimTracker.Id_Systems (ID)
,ANALYTIC_ID VARCHAR(30)
);

INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'2');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'4');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'6');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'8');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'10');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'12');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'14');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'16');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'18');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'20');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'22');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'24');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'26');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'28');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'30');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'32');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'34');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'36');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'38');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'40');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'42');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'44');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'46');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'48');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'50');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'52');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'54');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'56');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'58');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'60');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'62');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'64');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'66');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'68');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'70');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'72');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'74');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'76');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'78');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'80');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'82');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'84');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'86');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'88');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'90');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'92');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'94');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'96');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'98');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'100');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'102');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'104');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'106');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'108');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'110');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'112');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'114');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'116');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'118');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'120');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'122');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'124');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'126');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'128');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'130');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'132');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'134');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'136');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'138');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'140');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'142');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'144');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'146');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'148');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'150');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'152');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'154');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'156');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'158');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'160');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'162');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'164');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'166');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'168');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'170');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'172');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'174');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'176');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'178');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'180');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'182');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'184');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'186');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'188');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'190');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'192');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'194');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'196');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'198');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'200');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'202');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'204');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'206');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'208');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'210');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'212');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'214');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'216');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'218');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'220');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'222');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'224');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'226');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'228');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'230');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'232');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'234');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'236');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'238');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'240');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'242');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'244');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'246');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'248');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'250');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'252');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'254');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'256');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'258');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'260');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'262');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'264');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'266');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'268');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'270');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'272');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'274');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'276');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'278');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'280');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(1,'282');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NCTYPYO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AUVXXCW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XDWEKIL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZBZLBFK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FBTNEBQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XWZMJXZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SWHOWTF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FDQUTWO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KQLKBLR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AWFKEDX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PSKMUVG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LCBUZSA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YERQTUS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ERINRKY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MSZQATQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FRLSWTG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NPJHJUG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YMWYMLI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WJUNSLD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FJNWXCH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FCKPIJE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CSMURKG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ESGDPJN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NUYFUGU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PGVITMQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FGZNEQE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PYWOYCR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WGFCNDW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QQFQTYY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MMFMPKC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SPBANIX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZQIKNUC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RQVWNVU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KLTITBX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CKTNOGB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TSYIGJY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GFCWKJA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NIVYNFK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PZIZXDB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VHCSUFE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZVELBMN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KHZNUSJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'EBNCRLU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NKHMAXK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FTMIJOU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PRDOHSZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HEHIMFL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AXRVYGJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'USIHFZA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BFHHETC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DHUNSJS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XQQVGZW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XNOTEVR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QSZHQPQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UTMUIUL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FREOUTY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AFEOPBO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VCHWNXZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HOHLPMW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PXBVXYH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DDYUWYU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZGWFGZX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CCUXCSJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KOGVEIS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FCDSQSE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RXRRVZK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BAMWVVJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LQJBMJN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RXEUMIP');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MXRVPUT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OGQLPKY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QSUEZSA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XNLJORV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JEXAUQK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IRXKTLZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KYBRTHA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ASNMFAZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FCHFDNE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XZHOYBD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WHYWPQD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CGKEBHT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VHIVWRI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZXBJOGN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'EKQFZMY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NHLETEZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BSFRFIP');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CLIISOL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TMBZETN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AEQNBFH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NCQHBJI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QJROYQF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GIYOLJB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GCUZQIB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QADQQWH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MLWZDEI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'EUUXEYN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OBPVBNN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UMYFBMV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AQIJYYG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FSUDBNI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WBMNJVG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IZFBNKB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XULYTOA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FNAMNSG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YVHAFWR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DIFJMLG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IUJXLGE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WYDRKEV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LRYSOQO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XIFUASX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JFOLRWI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ANSVKHF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AOIYHGO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LECRVMI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BFJLWRH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CYPGMJW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JKKWMXI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NNYUBJC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FJWWGVC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZDIQOEG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JGFUCNW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XQOXOTA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NPCYSKF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KHOTEIT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JGHVTZA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PEYQUFK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IUYPQKC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UZGWHCX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AJFKRRD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DDOKGOO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YTFLFGB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YECLFHT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VIHTYML');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ELFSFQB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DVYMXPU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TPOHSXA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TMXMBFX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KSVSAWN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XFPWMZJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FVEKNBJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BVPDBQE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BXRKNUS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JVQKXFY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WIJNOKK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RZFRESN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PBEEIOG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OITKHOR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YNYVNTX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VJOTBHC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YMBJBEB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CASCWOX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RAJTORL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HFKCLJI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CIVWLZX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XSUUCJY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YYHVDMD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FOGVPWT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZZXKXLJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RDOQQSO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PFEBHYZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KGDIUJN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DFMQBKK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WQLMLNE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VHBZDIP');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TGASYSL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JEAZRXC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KLNAPMQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IWXKSFF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CKVEKFT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BZKKDMY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MCEEOOA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CUZKKOE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OLMESRJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SEZICSK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GEGESYS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NLOHPUA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HBHWHMH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RNHGZLJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NWEAKZW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DLOJJEA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HRMLIJD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SDSAFKZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OGNVHWK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ALBMEDX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZEKBRYL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YCVUGMY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JBCIEMQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OLCYRTD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KFXIHIC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IMZQXYK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GANBAPH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DGZVMBM');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GYCITNR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MKZKVHH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UULZWBZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JZSDLUP');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IHWQNEE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JPZWMMZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TMHVPIR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SRMUUPS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MVWNEET');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ILNDJYW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JVJWLRR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YPJHRDY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XXETJQV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QWKZSLY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JBUJWCV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LSAQHSJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DXTFONV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WLPUEXI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CVLBCKF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YLTMGMO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HAYBBPV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ALXQXXM');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GIVGNOV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ELBFKAF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NTXJYKV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UPREGDO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KWWDAOG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FVKCJHB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UJIPXXJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GNOVJPX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MKTGCFR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RIGYIKX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NVXGXEZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LKQKGKA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MCADRAV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KSRSFDA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ELPJSLT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GLUKWPS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UVFWREH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IAIUVOE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LJYNJVW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CWLZBWZ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IZJUDZI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'VJTMPUJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KMGVQII');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MZCAWJX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YIOGRRD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZRNSXIV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SMXNKAP');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LWCKXDF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ARYURRW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XXGRQMO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TJTAVQA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OMIGTGI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CYGJYAF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DMXUHBK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BSXUHJY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ATWVNOM');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AWWIGTG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JMKIVTC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'DLTPZGB');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HPGHWFN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'LMPYEHQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TPXQEBK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZVASBQD');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MKXWOVL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AOXYWCA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ERQCCJW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'FALRDGP');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OXKNKIE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XIUDPZG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YFKPMCV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NIPGHOG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SOLQLGW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GDCJJLW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RIYVCHY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PJQVFWM');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UGBVTOQ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'JHCIYDG');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'AODXZDI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QRBVWYX');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'PRVBPRE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZVMLTFC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'YBHZKFC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XNLNHAM');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NTLSKHN');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BYUNLUI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'UNKQWWY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'XPAVPQK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HHROWOY');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TCUOOEC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'KNPGNIL');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GTQEPIV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CTTIYKR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TGBYMBV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'SPNXGQR');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'GHKXVYS');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'OPBJXTO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HPVRGHM');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'MSTJFCI');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'IROYTGW');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'EUCBWJH');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ETKVWSA');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NYSHUYF');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NHQLBQE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ACJNMUO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'BDAIEJE');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HBFAEGC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'CXUUAQU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'QOOTLMJ');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RJLSQGC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'WXBHXZC');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'RIZDAGO');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'HTHTCXT');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'ZGWGYGV');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'USFWODK');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'TBBEWLU');
INSERT INTO ClaimTracker.Analytics (ID_SYSTEM_ID,ANALYTIC_ID ) 
VALUES(2,'NWPENCD');

CREATE TABLE ClaimTracker.Claim_Processing_Systems (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
,CLM_PROC_SYS VARCHAR(15)
);

INSERT INTO ClaimTracker.Claim_Processing_Systems (CLM_PROC_SYS)
	VALUES('CSP'),('COSMOS'),('UNET'),('OXHP'),('CIRRUS')('CAM');

CREATE TABLE ClaimTracker.Claim_Tracker (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
,USER_ID VARCHAR(15) NOT NULL
,CLAIM_ID VARCHAR(25) NOT NULL
,CLM_PROC_SYS_ID INT FOREIGN KEY REFERENCES ClaimTracker.Claim_Processing_Systems (ID)
,ID_SYSTEM_ID INT FOREIGN KEY REFERENCES ClaimTracker.Id_Systems (ID)
,ANALYTIC_ID_ID INT FOREIGN KEY REFERENCES ClaimTracker.Analytics (ID)
,START_TIME DATETIME
,STOP_TIME DATETIME
);

CREATE TABLE ClaimTracker.Comments (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
,CT_ID INT NOT NULL FOREIGN KEY REFERENCES ClaimTracker.Claim_Tracker (ID)
,Comment VARCHAR(2000)
);

GO
CREATE OR ALTER PROCEDURE ClaimTracker.Get_Analytics
AS
    SET NOCOUNT ON;
begin
select ID, ANALYTIC_ID from ClaimTracker.Analytics
end

GO

CREATE OR ALTER PROCEDURE ClaimTracker.Get_ID_Systems
AS
    SET NOCOUNT ON;
begin
select ID, ID_SYSTEM from ClaimTracker.ID_Systems
end

go

CREATE OR ALTER PROCEDURE ClaimTracker.Get_Claim_Processing_Systems
AS
    SET NOCOUNT ON;
begin
select ID, CLM_PROC_SYS from ClaimTracker.Claim_Processing_Systems
end